### ISSUE TITLE
Success with BR25 (AC6969D) Flashing!

### ISSUE THREAD

**Issue by bonayonpatrick** [christian-kramer/JieLi-AC690X-Familiarization#16]
After a full day of continuous research, I finally succeeded! I managed to change the name and remove the default tone sounds. 
![Screenshot_20240730-182853](https://github.com/user-attachments/assets/ade5e262-49cc-4cef-8e57-9dce050c14a9)

JieLi SDK Tool:
![image](https://github.com/user-attachments/assets/24d30fbf-3e6e-4e8d-b12f-0d400da0af77)
![image](https://github.com/user-attachments/assets/4fbcfcf6-1799-4d73-95bb-9f3edc24e4e7)

Tone resources deleted:
![image](https://github.com/user-attachments/assets/c2fbf34a-2cda-4f3f-8ac3-c000541cce78)

Although I still need to figure out how to convert MP3 files to WTG format to replace the default tones, I’m excited to share that I’ve successfully flashed the BR25 (AC6969D) thanks to the support from this GitHub community!

**Comment by dj-Topher** [comment]
Congrats. 
What SDK did you use? and did you have to do anything specific to get it to work with the 6969D? I have some 6969A's and want to give this a go.

**Comment by bonayonpatrick** [comment]
I am still working on the documentation, but I discovered that copying the original app.bin file from the chip's original firmware to the BR25 downloader resolved the issues with unresponsive buttons and the duplicate Bluetooth connection from the chip.

The app.bin file was the source of all the problems, and now the device is working completely fine with modified tone sounds and name without any issues.

**Comment by AnishSaini100** [comment]
I really want to know what sounds did you put, send me the mp3 files of it. Also, where did you get this software from? How did you manage to bring the buttons and led back?


You were able to do it because of my help.

**Comment by AnishSaini100** [comment]
> I am still working on the documentation, but I discovered that copying the original app.bin file from the chip's original firmware to the BR25 downloader resolved the issues with unresponsive buttons and the duplicate Bluetooth connection from the chip.
> 
> The app.bin file was the source of all the problems, and now the device is working completely fine with modified tone sounds and name without any issues.

Where did you get this software from? It looks like an enhanced version of the bt_config_tools.exe

How did you modify app.bin manage to bring the buttons and led back? Where is app.bin?

How did you extract files from the chip?

You were able to do it because of my help.

**Comment by AnishSaini100** [comment]
I made a custom Bluetooth audio PCB and the chip is AC6956C8 which is br23 so can you find me the tool to do it with br23

**Comment by AnishSaini100** [comment]
What does multiple names do

**Comment by Papperskatt** [comment]
This is very very interesting. Amazing work! I really look forward to seeing your documentation whenever you release it.

I've been experimenting a bit with Qualcomm BT chips for a while as I had given up hope about JL chips. The Qualcomm chips are quite expensive so I would love to finally be able to program JL chips instead.

**Comment by bonayonpatrick** [comment]
@AnishSaini100  Yes, but Kagamiq did solve the issue.

I got the AC696x SDK from a Russian forum. Although my method only works for the AC6969D chip, I tried the same approach with the AC6965A, but it doesn't work because the app.bin seems to be built differently.

I extracted the chip contents using jluboottool. To extract the files, you need to decrypt the dump file and identify the Start of File (SOF) and End of File (EOF) within the chip dump.

I didn’t modify the app.bin; I copied it directly from the dump file to the downloader. 
I'm also translating the Chinese comments in the code to English and cleaned up the downloader to make it easier to use.
![image](https://github.com/user-attachments/assets/a179d722-cfe3-4f24-8ec9-92ce12c8e521)

The multiple names issue might be related to Bluetooth serial debugging purposes, but I still haven't tested that yet.

My documentation is still unfinished because this is my first time doing it. I'm not a college, high school, or elementary student.

**Comment by bonayonpatrick** [comment]
@Papperskatt 

JieLi chips seem so perfect. They only cost $0.50, which is cheaper than my $2 ESP32. They come with high-quality 16-bit ADC and DAC, Bluetooth, SPI, I2C, and a 160MHz Pi32V2 processor. I want to make a simple blinker using this chip since I can compile the SDK and upload it, but I'm not a C/C++ programmer—I mainly use Python.

**Comment by bonayonpatrick** [comment]
Oh, sorry, I accidentally pressed "Close with comment".

**Comment by bonayonpatrick** [comment]
So I got it working: a blinky LED example on the AC6965A. Since I can't modify the tone and name on this chip, I'm just using it as my JieLi MCU 😌

https://github.com/user-attachments/assets/13f34fde-2347-4bc0-8310-b817836a8c1f


![image](https://github.com/user-attachments/assets/47fbc823-951d-43d8-8c73-25a59244eed7)

**Comment by AnishSaini100** [comment]
> So I got it working: a blinky LED example on the AC6965A. Since I can't modify the tone and name on this chip, I'm just using it as my JieLi MCU 😌
> 
>  video.mp4 
> ![image](https://private-user-images.githubusercontent.com/89962755/354518826-47fbc823-951d-43d8-8c73-25a59244eed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTQyODgsIm5iZiI6MTcyMjYxMzk4OCwicGF0aCI6Ii84OTk2Mjc1NS8zNTQ1MTg4MjYtNDdmYmM4MjMtOTUxZC00M2Q4LThjNzMtMjVhNTkyNDRlZWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1NTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOGQwMWRiNjFhZjcwYzMxZjE0MmUzZGFlMjUwYzczMWJkNTUxOTFkMDYzNWUxYzFhMjhiN2E0NDExYzAwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ehxZEG_TLt5pdfFRNCar4fgwzH_X56Rmdvunj_naNLM)

Please provide the link or attatch the file for the software you found on the russian forum

**Comment by bonayonpatrick** [comment]
Here
https://drive.google.com/file/d/1lWuF5vjkJ9df9nuc6K-6UjyQP6KJse9Y/view?usp=drivesdk

**Comment by dj-Topher** [comment]
> Here https://drive.google.com/file/d/1lWuF5vjkJ9df9nuc6K-6UjyQP6KJse9Y/view?usp=drivesdk

by chance, do you have the password for the extraction?

**Comment by bonayonpatrick** [comment]
Oh sorry i forgot to include the password, it's 1111

**Comment by dj-Topher** [comment]
> Oh sorry i forgot to include the password, it's 1111

lol why wouldnt it be 1111. Thanks, I'm going to give this a shot at the 6969A. I think it should work no problem, but will let you know.
My eventual plan is to make a RP zero or just straight 2040, man in the middle. USB style stick that you cn just plug in, it will inject the code to put the chip into programming mode. then dump the fm, and possibly even just open up a python script that asks for UUID then reflash. but we shall see

**Comment by bonayonpatrick** [comment]
Programming the AC6969A is guaranteed a success, just like what I did with the AC6969D and AC6965A. Now I don't have any JL chip to crack 😆.

Yeah, I read the SDK code and saw the UBOOT section code that reads bootloaderizer signals, so maybe I can change it by just pressing a button to enter UBOOT mode or make it like a straightforward dev board, maybe I'll make one myself.

After some digging and reading the gibberish-looking hex file, I finally cracked it, so I made a Python script that extracts every file, including app.bin, inside the AC6969D and AC6965A as I tested, also found the end of the firmware section, so I can basically just swap that chip's firmware with another chip's firmware because coding the app.bin is really hard.

The only thing I want to do now is make a Python code to enter UBOOT mode without the bootloaderizer.

**Comment by bonayonpatrick** [comment]
Can you send me your dump file when you extracted it? I'm just curious what's inside your AC6969A and if it's the same as mine.

**Comment by AnishSaini100** [comment]
I can't find the software for modifying sounds

I want this software:

![image](https://github.com/user-attachments/assets/c29c7881-eb79-4425-9ec7-b4791bd448bf)

**Comment by bonayonpatrick** [comment]
here: [jieli-sdk](https://drive.google.com/file/d/1rW0mNFwPPpAEz550WjNqROevvuMiz7Y1/view?usp=sharing)

**Comment by AnishSaini100** [comment]
@bonayonpatrick

You asked how to convert .wtg to mp3.

You don't need to convert it. Just select any supported audio file like wav or mp3 and it will automatically convert it for you.

Also, instead of wtg which is low quality, you can change it to a higher quality version if there is enough space. I would .mty recommend 44.1khz and 48kbps. If the IC is low on space.

To change the format, there is a dropdown menu at bottom right of the window (main format) and select a format, I would recommend .mty format. But you have to reupload the audio files because they don't automatically change.

**Comment by bonayonpatrick** [comment]
Thank you! I appreciate it. I'm currently facing a challenge with reverse engineering the app.bin file on Jieli chips.

I've been researching these chips thoroughly and am learning C and assembly to program them directly from the SDK. I've also developed an ESP8266 debugger that sends signals to enter U-BOOT mode and reads the UART debug output to capture all the logs generated by the chip. The MH-M18 module has been great for my development because I can use the MUTE and KEY pins as TX and dummy GPIO or ADC pins to read user inputs.

However, some of the chips don't support high-quality tones like MTY and AAC because the app.bin file doesn't include the AAC or MTY codec.

Additionally, I'm considering creating a development board to further expand the functionality of my projects.

**Comment by AnishSaini100** [comment]
@bonayonpatrick 

Please tell me the reason why you set a password

**Comment by bonayonpatrick** [comment]
That's not my file and it belongs to someone else. I didn't set a password for it.
